package finance_report

type BalanceSheetData struct {
	AccountsPayable                                        int
	AccountsPayable_per                                    int
	AccountsReceivableNet                                  int
	AccountsReceivableNet_per                              int
	CapitalStock                                           int
	CapitalStock_per                                       int
	CapitalSurplus                                         int
	CapitalSurplus_per                                     int
	CapitalSurplusAdditionalPaidInCapital                  int
	CapitalSurplusAdditionalPaidInCapital_per              int
	CashAndCashEquivalents                                 int
	CashAndCashEquivalents_per                             int
	CurrentAssets                                          int
	CurrentAssets_per                                      int
	CurrentLiabilities                                     int
	CurrentLiabilities_per                                 int
	CurrentProvisions                                      int
	CurrentProvisions_per                                  int
	DeferredTaxAssets                                      int
	DeferredTaxAssets_per                                  int
	Equity                                                 int
	Equity_per                                             int
	EquityAttributableToOwnersOfParent                     int
	EquityAttributableToOwnersOfParent_per                 int
	EquivalentIssueSharesOfAdvanceReceiptsForOrdinaryShare int
	IntangibleAssets                                       int
	IntangibleAssets_per                                   int
	Inventories                                            int
	Inventories_per                                        int
	LegalReserve                                           int
	LegalReserve_per                                       int
	Liabilities                                            int
	Liabilities_per                                        int
	LongtermBorrowings                                     int
	LongtermBorrowings_per                                 int
	NoncontrollingInterests                                int
	NoncontrollingInterests_per                            int
	NoncurrentAssets                                       int
	NoncurrentAssets_per                                   int
	NoncurrentLiabilities                                  int
	NoncurrentLiabilities_per                              int
	NumberOfSharesInEntityHeldByEntityAndByItsSubsidiaries int
	OrdinaryShare                                          int
	OrdinaryShare_per                                      int
	OtherCurrentAssets                                     int
	OtherCurrentAssets_per                                 int
	OtherCurrentLiabilities                                int
	OtherCurrentLiabilities_per                            int
	OtherEquityInterest                                    int
	OtherEquityInterest_per                                int
	OtherNoncurrentAssets                                  int
	OtherNoncurrentAssets_per                              int
	OtherNoncurrentLiabilities                             int
	OtherNoncurrentLiabilities_per                         int
	OtherPayables                                          int
	OtherPayables_per                                      int
	OtherReceivable                                        int
	OtherReceivable_per                                    int
	PropertyPlantAndEquipment                              int
	PropertyPlantAndEquipment_per                          int
	RetainedEarnings                                       int
	RetainedEarnings_per                                   int
	UnappropriatedRetainedEarningsAaccumulatedDeficit      int
	UnappropriatedRetainedEarningsAaccumulatedDeficit_per  int
}
